### ISSUE TITLE
1.20.1 update?

### ISSUE THREAD

**Issue by aglarcz** [Crazy-Crew/BlockParticles#27]
### Server Version

1.19.3

### Server Platform

Paper

### Describe the bug

...

### Steps to reproduce

...

### Additional context

Hi, any chance for 1.20.1 update? I tried to compile from this github but its failing due to your API missing (broken repo).

### Agreements

- [X] I have searched for and ensured there isn't already an open issue regarding this.
- [X] I ticked all the boxes without actually reading them
- [X] My version of Minecraft is supported by CrazyCrew.

**Comment by ryderbelserion** [comment]
ok

**Comment by ryderbelserion** [comment]
Updating to 1.20.1 with improvements and more config options. It's basically will be a whole new plugin so recommendation when it releases is to wipe your configurations.

**Comment by aglarcz** [comment]
Okay, great. Thanks for your time.
